// LIVCK agent <-> pulse wire protocol, version 1.
//
// FROZEN. The first public commit of this file is the freeze point. Only
// additive changes are allowed after that (new fields with new numbers, new
// enum values). Never renumber, retype, or reuse a field number, and never
// remove or repurpose a reserved range. A breaking change here silently breaks
// production across two repos (agent + pulse). See CONTRACT.md, section
// "When you must change this contract".
//
// Transport: POST /v1/ingest, Content-Type application/x-protobuf,
// Content-Encoding zstd, Authorization: Bearer lvk_...

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wire.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType is the closed event catalog. Adding a value is additive; removing or
// renumbering is breaking. Value 0 is the proto3 default: an agent that sends a
// type the server does not know maps to UNSPECIFIED and the event is dropped.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// Agent installed / enrolled. meta: version.
	EventType_EVENT_TYPE_INSTALL EventType = 1
	EventType_EVENT_TYPE_ENROLL  EventType = 2
	// First run after a reboot. meta: boot_id, downtime_seconds (optional).
	EventType_EVENT_TYPE_BOOT EventType = 3
	// Dirty boot: new boot_id with no clean_shutdown before it. meta:
	// downtime_seconds.
	EventType_EVENT_TYPE_UNEXPECTED_REBOOT EventType = 4
	// logind ScheduledShutdown change. meta: type (reboot/poweroff), at, reason.
	EventType_EVENT_TYPE_REBOOT_SCHEDULED EventType = 5
	// logind PrepareForShutdown plus delay-inhibitor lock. meta: type, reason
	// (optional).
	EventType_EVENT_TYPE_CLEAN_SHUTDOWN EventType = 6
	// OOM kill from /proc/vmstat delta. meta: count (v1 has no comm/process).
	EventType_EVENT_TYPE_OOM_KILL EventType = 7
	// Mount went read-only. meta: mount.
	EventType_EVENT_TYPE_FS_READONLY EventType = 8
	// Mount reached 100 percent. meta: mount.
	EventType_EVENT_TYPE_DISK_FULL EventType = 9
	// Clock skew above 30s detected. meta: skew_ms.
	EventType_EVENT_TYPE_CLOCK_SKEW_DETECTED EventType = 10
	// Self-updater. meta: from, to, error (optional).
	EventType_EVENT_TYPE_AGENT_UPDATE_STARTED EventType = 11
	EventType_EVENT_TYPE_AGENT_UPDATE_APPLIED EventType = 12
	EventType_EVENT_TYPE_AGENT_UPDATE_FAILED  EventType = 13
	// Config module. meta: version, error (optional).
	EventType_EVENT_TYPE_CONFIG_APPLIED EventType = 14
	EventType_EVENT_TYPE_CONFIG_ERROR   EventType = 15
	// RAM ring dropped reports. meta: dropped_count.
	EventType_EVENT_TYPE_BUFFER_OVERFLOW EventType = 16
	// livck-agent uninstall (best effort).
	EventType_EVENT_TYPE_UNINSTALL EventType = 17
	// systemd unit feature. meta: unit, exec_status (optional), n_restarts.
	EventType_EVENT_TYPE_UNIT_FAILED    EventType = 18
	EventType_EVENT_TYPE_UNIT_RESTARTED EventType = 19
	EventType_EVENT_TYPE_UNIT_FLAPPING  EventType = 20
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_INSTALL",
		2:  "EVENT_TYPE_ENROLL",
		3:  "EVENT_TYPE_BOOT",
		4:  "EVENT_TYPE_UNEXPECTED_REBOOT",
		5:  "EVENT_TYPE_REBOOT_SCHEDULED",
		6:  "EVENT_TYPE_CLEAN_SHUTDOWN",
		7:  "EVENT_TYPE_OOM_KILL",
		8:  "EVENT_TYPE_FS_READONLY",
		9:  "EVENT_TYPE_DISK_FULL",
		10: "EVENT_TYPE_CLOCK_SKEW_DETECTED",
		11: "EVENT_TYPE_AGENT_UPDATE_STARTED",
		12: "EVENT_TYPE_AGENT_UPDATE_APPLIED",
		13: "EVENT_TYPE_AGENT_UPDATE_FAILED",
		14: "EVENT_TYPE_CONFIG_APPLIED",
		15: "EVENT_TYPE_CONFIG_ERROR",
		16: "EVENT_TYPE_BUFFER_OVERFLOW",
		17: "EVENT_TYPE_UNINSTALL",
		18: "EVENT_TYPE_UNIT_FAILED",
		19: "EVENT_TYPE_UNIT_RESTARTED",
		20: "EVENT_TYPE_UNIT_FLAPPING",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":          0,
		"EVENT_TYPE_INSTALL":              1,
		"EVENT_TYPE_ENROLL":               2,
		"EVENT_TYPE_BOOT":                 3,
		"EVENT_TYPE_UNEXPECTED_REBOOT":    4,
		"EVENT_TYPE_REBOOT_SCHEDULED":     5,
		"EVENT_TYPE_CLEAN_SHUTDOWN":       6,
		"EVENT_TYPE_OOM_KILL":             7,
		"EVENT_TYPE_FS_READONLY":          8,
		"EVENT_TYPE_DISK_FULL":            9,
		"EVENT_TYPE_CLOCK_SKEW_DETECTED":  10,
		"EVENT_TYPE_AGENT_UPDATE_STARTED": 11,
		"EVENT_TYPE_AGENT_UPDATE_APPLIED": 12,
		"EVENT_TYPE_AGENT_UPDATE_FAILED":  13,
		"EVENT_TYPE_CONFIG_APPLIED":       14,
		"EVENT_TYPE_CONFIG_ERROR":         15,
		"EVENT_TYPE_BUFFER_OVERFLOW":      16,
		"EVENT_TYPE_UNINSTALL":            17,
		"EVENT_TYPE_UNIT_FAILED":          18,
		"EVENT_TYPE_UNIT_RESTARTED":       19,
		"EVENT_TYPE_UNIT_FLAPPING":        20,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

// MetricBatch is one ingest request body: reports and/or events collected by an
// agent, sent to pulse. A batch may carry only events (empty reports) or only
// reports.
type MetricBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wire schema version. Must be 1 in v1. 0 => 400 UNSUPPORTED_SCHEMA_VERSION.
	// Deprecation band: pulse fully accepts {N, N-1}, accepts N-2..min_supported
	// with a warning, rejects below min_supported with 400. min_supported is
	// published in /v1/me and pulse config.
	SchemaVersion uint32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// UUIDv4 batch idempotency key. Longer than 64 chars => 400
	// IDEMPOTENCY_KEY_TOO_LONG. Not UUIDv4 form => 400 MALFORMED_BODY.
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Agent build version, e.g. "1.0.0".
	AgentVersion string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Agent instance UUID from the state directory. Also the clone signal: pulse
	// compares it against the bound_instance_id in the token claims; a mismatch
	// is 409 INSTANCE_CONFLICT. No separate wire field carries the binding.
	AgentInstanceId string `protobuf:"bytes,4,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"`
	// Wall clock send time, milliseconds. Used only to measure skew. |skew| > 5
	// min => 422 CLOCK_SKEW (batch is final; a 422 does not refresh liveness,
	// only a 2xx does). Sample timestamps live on each Report, not here.
	SentAtUnixMs int64 `protobuf:"varint,5,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	// Config version the agent currently has applied (echo). pulse piggybacks the
	// authoritative version in the response so the agent knows to pull config.
	AppliedConfigVersion uint32 `protobuf:"varint,6,opt,name=applied_config_version,json=appliedConfigVersion,proto3" json:"applied_config_version,omitempty"`
	// Host fingerprint: machine_id_hash, boot_id, cloud_instance_id (optional),
	// hostname. Sent on the first batch after start and whenever it changes.
	Fingerprint map[string]string `protobuf:"bytes,7,rep,name=fingerprint,proto3" json:"fingerprint,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 1..200 reports. More than one is backfill. Server enforces caps.max_reports.
	Reports []*Report `protobuf:"bytes,8,rep,name=reports,proto3" json:"reports,omitempty"`
	// 1..20 events, enforced server side (caps.max_events). Overflow is dropped
	// item-wise with reason "event_budget", never a batch reject.
	Events []*Event `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty"`
	// Empty for managed tokens (otherwise 400 SERVICE_ADDRESSING_FORBIDDEN).
	// Required and claims-matched for user tokens; empty for a user
	// token => 400 SERVICE_ADDRESSING_REQUIRED.
	ServicePublicId string `protobuf:"bytes,10,opt,name=service_public_id,json=servicePublicId,proto3" json:"service_public_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (x *MetricBatch) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *MetricBatch) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *MetricBatch) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *MetricBatch) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *MetricBatch) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *MetricBatch) GetAppliedConfigVersion() uint32 {
	if x != nil {
		return x.AppliedConfigVersion
	}
	return 0
}

func (x *MetricBatch) GetFingerprint() map[string]string {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *MetricBatch) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *MetricBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *MetricBatch) GetServicePublicId() string {
	if x != nil {
		return x.ServicePublicId
	}
	return ""
}

// Report is one aggregation window of sys.* (and later custom.*) metrics.
type Report struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wall clock at the END of the aggregation window, milliseconds. Sample time,
	// never send time: retried batches must not collapse.
	SampledAtUnixMs int64 `protobuf:"varint,1,opt,name=sampled_at_unix_ms,json=sampledAtUnixMs,proto3" json:"sampled_at_unix_ms,omitempty"`
	// Metric values. sys.* keys are the fixed catalog in catalog.json; custom.*
	// keys are rejected in v1. An empty map is allowed (event-carrier batch).
	Metrics map[string]float64 `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Report-level metadata, flat. Sent on change and on the first report after
	// start. Never carries ips_* (IP data is enroll-only). Optional key
	// window_samples marks a partial window.
	Meta          map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Report) GetSampledAtUnixMs() int64 {
	if x != nil {
		return x.SampledAtUnixMs
	}
	return 0
}

func (x *Report) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Report) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Event is a discrete lifecycle or health signal. Dedupe anchor is event_id;
// pulse sets the dedupe key only after a successful produce (mark-after-deliver).
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv4. Dedupe anchor.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Wall clock when the event occurred, milliseconds.
	OccurredAtUnixMs int64 `protobuf:"varint,2,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"`
	// Event type. An unknown enum value is dropped by the server plus counted.
	Type EventType `protobuf:"varint,3,opt,name=type,proto3,enum=livck.wire.v1.EventType" json:"type,omitempty"`
	// Type-validated metadata. reason, if present, is capped at 200 chars.
	Meta          map[string]string `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_wire_proto protoreflect.FileDescriptor

const file_wire_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wire.proto\x12\rlivck.wire.v1\"\xab\x04\n" +
	"\vMetricBatch\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12*\n" +
	"\x11agent_instance_id\x18\x04 \x01(\tR\x0fagentInstanceId\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x05 \x01(\x03R\fsentAtUnixMs\x124\n" +
	"\x16applied_config_version\x18\x06 \x01(\rR\x14appliedConfigVersion\x12M\n" +
	"\vfingerprint\x18\a \x03(\v2+.livck.wire.v1.MetricBatch.FingerprintEntryR\vfingerprint\x12/\n" +
	"\areports\x18\b \x03(\v2\x15.livck.wire.v1.ReportR\areports\x12,\n" +
	"\x06events\x18\t \x03(\v2\x14.livck.wire.v1.EventR\x06events\x12*\n" +
	"\x11service_public_id\x18\n" +
	" \x01(\tR\x0fservicePublicId\x1a>\n" +
	"\x10FingerprintEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x14\x10\x1e\"\xa3\x02\n" +
	"\x06Report\x12+\n" +
	"\x12sampled_at_unix_ms\x18\x01 \x01(\x03R\x0fsampledAtUnixMs\x12<\n" +
	"\ametrics\x18\x02 \x03(\v2\".livck.wire.v1.Report.MetricsEntryR\ametrics\x123\n" +
	"\x04meta\x18\x03 \x03(\v2\x1f.livck.wire.v1.Report.MetaEntryR\x04meta\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\n" +
	"\x10\x0f\"\xf2\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12-\n" +
	"\x13occurred_at_unix_ms\x18\x02 \x01(\x03R\x10occurredAtUnixMs\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.livck.wire.v1.EventTypeR\x04type\x122\n" +
	"\x04meta\x18\x04 \x03(\v2\x1e.livck.wire.v1.Event.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\n" +
	"\x10\x0f*\xfd\x04\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_INSTALL\x10\x01\x12\x15\n" +
	"\x11EVENT_TYPE_ENROLL\x10\x02\x12\x13\n" +
	"\x0fEVENT_TYPE_BOOT\x10\x03\x12 \n" +
	"\x1cEVENT_TYPE_UNEXPECTED_REBOOT\x10\x04\x12\x1f\n" +
	"\x1bEVENT_TYPE_REBOOT_SCHEDULED\x10\x05\x12\x1d\n" +
	"\x19EVENT_TYPE_CLEAN_SHUTDOWN\x10\x06\x12\x17\n" +
	"\x13EVENT_TYPE_OOM_KILL\x10\a\x12\x1a\n" +
	"\x16EVENT_TYPE_FS_READONLY\x10\b\x12\x18\n" +
	"\x14EVENT_TYPE_DISK_FULL\x10\t\x12\"\n" +
	"\x1eEVENT_TYPE_CLOCK_SKEW_DETECTED\x10\n" +
	"\x12#\n" +
	"\x1fEVENT_TYPE_AGENT_UPDATE_STARTED\x10\v\x12#\n" +
	"\x1fEVENT_TYPE_AGENT_UPDATE_APPLIED\x10\f\x12\"\n" +
	"\x1eEVENT_TYPE_AGENT_UPDATE_FAILED\x10\r\x12\x1d\n" +
	"\x19EVENT_TYPE_CONFIG_APPLIED\x10\x0e\x12\x1b\n" +
	"\x17EVENT_TYPE_CONFIG_ERROR\x10\x0f\x12\x1e\n" +
	"\x1aEVENT_TYPE_BUFFER_OVERFLOW\x10\x10\x12\x18\n" +
	"\x14EVENT_TYPE_UNINSTALL\x10\x11\x12\x1a\n" +
	"\x16EVENT_TYPE_UNIT_FAILED\x10\x12\x12\x1d\n" +
	"\x19EVENT_TYPE_UNIT_RESTARTED\x10\x13\x12\x1c\n" +
	"\x18EVENT_TYPE_UNIT_FLAPPING\x10\x14B&Z$github.com/LIVCK/agent/pkg/wire;wireb\x06proto3"

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData []byte
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)))
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wire_proto_goTypes = []any{
	(EventType)(0),      // 0: livck.wire.v1.EventType
	(*MetricBatch)(nil), // 1: livck.wire.v1.MetricBatch
	(*Report)(nil),      // 2: livck.wire.v1.Report
	(*Event)(nil),       // 3: livck.wire.v1.Event
	nil,                 // 4: livck.wire.v1.MetricBatch.FingerprintEntry
	nil,                 // 5: livck.wire.v1.Report.MetricsEntry
	nil,                 // 6: livck.wire.v1.Report.MetaEntry
	nil,                 // 7: livck.wire.v1.Event.MetaEntry
}
var file_wire_proto_depIdxs = []int32{
	4, // 0: livck.wire.v1.MetricBatch.fingerprint:type_name -> livck.wire.v1.MetricBatch.FingerprintEntry
	2, // 1: livck.wire.v1.MetricBatch.reports:type_name -> livck.wire.v1.Report
	3, // 2: livck.wire.v1.MetricBatch.events:type_name -> livck.wire.v1.Event
	5, // 3: livck.wire.v1.Report.metrics:type_name -> livck.wire.v1.Report.MetricsEntry
	6, // 4: livck.wire.v1.Report.meta:type_name -> livck.wire.v1.Report.MetaEntry
	0, // 5: livck.wire.v1.Event.type:type_name -> livck.wire.v1.EventType
	7, // 6: livck.wire.v1.Event.meta:type_name -> livck.wire.v1.Event.MetaEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		EnumInfos:         file_wire_proto_enumTypes,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
